### PR TITLE
MSFT_xRDSessionCollection: Workaround for bug in Windows Server 2019

### LINKED ISSUE #91: MSFT_xRDSessionCollection: Collection related DSC fails when multiple collections are present
#### Details of the scenario you tried and the problem that is occurring
xRDSessionCollection DSC fails on Windows Server 2019 if multiple RD Session Collections are present

#### Suggested solution to the issue
Issue is caused by malfunctioning Get-RDSessionCollection cmdlet in Windows Server 2019. 
Microsoft will need to address the underlying issue.
I'll be submitting a Pull Request with  a workaround for the MSFT_xRDSessionCollection DSC Resource.

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
PSVersion                      5.1.17763.1490
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1490
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### PR DESCRIPTION
**Pull request by RobBiddle**
MSFT_xRDSessionCollection: Workaround for bug in Windows Server 2019

#### Pull Request (PR) description
Workaround for Get-RDSessionCollection bug in Windows Server 2019.

#### This Pull Request (PR) fixes the following issues
Fixes #91 

#### Task list
- [x] Added an entry under the Unreleased section of file CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/92)

### CODE REVIEW

**Comment by RobBiddle** [comment]
@danielboth Is there anything else I need to do for this PR to be accepted? 
Any questions about the issue https://github.com/dsccommunity/xRemoteDesktopSessionHost/issues/91 this PR resolves?

**Comment by danielboth** [comment]
Hey Rob, are you up for writing a test for this PR as well? For example, you could write a test where the call to Get-RDSessionCollection returns 2 results and then ensure that the correct one is picked from that result. Other than that, PR looks good to me.

**Comment by nyanhp** [comment]
@danielboth is there anything I can help with to move this PR along? Two of my customers have the same issue, and were able to validate the solution that was proposed here.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/92#-:-N7-_F_0-nSRhE8HThZE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RobBiddle)

**Pull request merged**
