### PR TITLE
xRDRemoteApp: Allow for multiple values with UserGroups parameter

### LINKED ISSUE #87: xRDRemoteApp: Allow for an array of values for the UserGroups parameter
#### Details of the scenario you tried and the problem that is occurring
The `UserGroups` parameter only accepts a single string, when it should support supplying an array of values.

#### Suggested solution to the issue
Allow for supplying an array of values to the `UserGroups` parameter.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

### PR DESCRIPTION
**Pull request by jeremyciak**
#### Pull Request (PR) description

This PR implements a mechanism to allow for multiple values to be supplied to the `UserGroups` parameter

#### This Pull Request (PR) fixes the following issues

- Fixes #87 

#### Task list

- [x] Added an entry under the Unreleased section of file CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/88)

### CODE REVIEW

**Comment by jeremyciak** [comment]
@danielboth, I would love to get your feedback on this as soon as you're able to. This is a fairly straightforward adjustment. For whatever reason I have issues on my local machine trying to successfully build, but it could likely be due to my usage of PowerShell 7.1.0. It looks like all the builds passed in the CI/CD pipeline though.

**Review by danielboth — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/88)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @jeremyciak)

___
*[source/DSCResources/MSFT_xRDRemoteApp/MSFT_xRDRemoteApp.psm1, line 52 at r1](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/88#-MMlQkvj7XESvJgEW9OI:-MMlQkvk-h84xIRRD4uH:ba1196c) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/0cb5c24dca0611bff10d072341baed772ec6a8b1/source/DSCResources/MSFT_xRDRemoteApp/MSFT_xRDRemoteApp.psm1#L52)):*
> ```PowerShell
>         [string] $IconPath,
>         [Parameter()]
>         [string[]] $UserGroups,
> ```

Not a specific comment for this line, but it would be good to add a unit test that proves we are now able to handle multiple values in $UserGroups.
___
*[source/DSCResources/MSFT_xRDRemoteApp/MSFT_xRDRemoteApp.psm1, line 225 at r1](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/88#-MMlMS1z8xLCRYyRnPzV:-MMlMS1z8xLCRYyRnPzW:bqsu2nt) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/0cb5c24dca0611bff10d072341baed772ec6a8b1/source/DSCResources/MSFT_xRDRemoteApp/MSFT_xRDRemoteApp.psm1#L225)):*
> ```PowerShell
>         TurnOffTypeChecking = $true
>         SortArrayValues     = $true
>         Verbose             = $verbose
> ```

$verbose doesn't seem to be defined?

**Review by jeremyciak — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/88)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @danielboth)

___
*[source/DSCResources/MSFT_xRDRemoteApp/MSFT_xRDRemoteApp.psm1, line 52 at r1](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/88#-MMlQkvj7XESvJgEW9OI:-MMpNRik3iXctozybxiQ:bantiw3) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/0cb5c24dca0611bff10d072341baed772ec6a8b1/source/DSCResources/MSFT_xRDRemoteApp/MSFT_xRDRemoteApp.psm1#L52)):*
<details><summary><i>Previously, danielboth (Daniël) wrote…</i></summary><blockquote>

Not a specific comment for this line, but it would be good to add a unit test that proves we are now able to handle multiple values in $UserGroups.
</blockquote></details>

I intended to add to the unit testing but I was hoping to get some feedback from you on the failure(s) I am experiencing with the build process locally. I can try to muscle through locally anyway, but I figured I would be able to contribute to the testing more meaningfully if I could build successfully.
___
*[source/DSCResources/MSFT_xRDRemoteApp/MSFT_xRDRemoteApp.psm1, line 225 at r1](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/88#-MMlMS1z8xLCRYyRnPzV:-MMpN2kQ7lkdY7U_63Kt:b-rmmvnj) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/0cb5c24dca0611bff10d072341baed772ec6a8b1/source/DSCResources/MSFT_xRDRemoteApp/MSFT_xRDRemoteApp.psm1#L225)):*
<details><summary><i>Previously, danielboth (Daniël) wrote…</i></summary><blockquote>

$verbose doesn't seem to be defined?
</blockquote></details>

You're right, I copied this block from what I implemented previously for the **xRDSessionCollectionConfiguration** `Test-TargetResource` cmdlet. I have removed the `Verbose` parameter from the hash object.

**Comment by gaelcolas** [comment]
@jeremyciak the build should work on PS7, but the tests (i.e. hqrmtest) may not work (depending on modules, dependencies, how the code is written and all). Logs/error message would help finding the reasons, but PS7 is not supported for all modules.
You can also follow this doc here to build your Fork (instead of just the PRs).
https://dsccommunity.org/blog/convert-a-module-for-continuous-delivery/#attach-your-fork-to-a-free-azure-devops-organization

**Comment by jeremyciak** [comment]
@gaelcolas, I addressed some other things that were failing with unit test structures but the one remaining that I believe is preventing build completion seems to be with **PS Script Analyzer**. I get an error where it says it is executing script `PSSAResource.common.Tests.ps1` and then on this (sanitized):

```powershell
  Describing Common Tests - PS Script Analyzer on Resource Files
WARNING: The tests for Common Tests - New Error-Level Script Analyzer Rules, NewErrorPSSA is not being enforced. Please Opt-in!
    [-] Error occurred in Describe block 0ms
      FileLoadException: Assembly with same name is already loaded
      at <ScriptBlock>, C:\Users\username\Documents\Git\GitHub\xRemoteDesktopSessionHost\output\RequiredModules\PSScriptAnalyzer\1.19.1\PSScriptAnalyzer.psm1: line 36
      at <ScriptBlock>, C:\Users\username\Documents\Git\GitHub\xRemoteDesktopSessionHost\output\RequiredModules\DscResource.Test\0.14.1\Tests\QA\PSSAResource.common.Tests.ps1: line 73
      at DescribeImpl, C:\Users\username\Documents\Git\GitHub\xRemoteDesktopSessionHost\output\RequiredModules\Pester\4.10.1\Functions\Describe.ps1: line 213
```

**Review by danielboth — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/88)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @jeremyciak)

___
*[source/DSCResources/MSFT_xRDRemoteApp/MSFT_xRDRemoteApp.psm1, line 52 at r1](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/88#-MMlQkvj7XESvJgEW9OI:-MMr8sxd4S8QVy1BhYqn:b88rlbj) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/0cb5c24dca0611bff10d072341baed772ec6a8b1/source/DSCResources/MSFT_xRDRemoteApp/MSFT_xRDRemoteApp.psm1#L52)):*
<details><summary><i>Previously, jeremyciak (Jeremy Ciak) wrote…</i></summary><blockquote>

I intended to add to the unit testing but I was hoping to get some feedback from you on the failure(s) I am experiencing with the build process locally. I can try to muscle through locally anyway, but I figured I would be able to contribute to the testing more meaningfully if I could build successfully.
</blockquote></details>

Got it, I'm afraid though that xRemoteDesktopSessionHost, since it depends on the RemoteDesktop module is not the perfect candidate to build with PS 7.1. That is mainly because this module is loaded through the WinPSCompatSession in PS7. Also, when run through DSC, PowerShell 5.1 will be used to execute, so it makes sense to keep using that for building as well (at least for the moment).

I've also noticed you already succeeded in adding some unit tests, good job!
___
*[tests/Unit/MSFT_xRDRemoteApp.tests.ps1, line 135 at r2](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/88#-MMrAW_gDbGXiZEhl6lO:-MMrAW_gDbGXiZEhl6lP:b-mi74gs) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/134e0f213d960bbfa86c05b31db1ed7aa5bfe0b7/tests/Unit/MSFT_xRDRemoteApp.tests.ps1#L135)):*
> ```PowerShell
>                 It 'Should generate an error, given that the CollectionName is not found in the SessionDeployment' {
>                     { Get-TargetResource @xRDRemoteAppSplat -ErrorAction Stop } |
>                         Should -Throw 'Failed to lookup RD Session Collection TestCollection. Error: Collection not found!'
> ```

I agree this is better that the try - catch approach, please do use -ExpectedMessage though instead of relying on positional parameters.
___
*[tests/Unit/MSFT_xRDRemoteApp.tests.ps1, line 197 at r2](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/88#-MMrAmL71ihHkhLN2E6J:-MMrAmL71ihHkhLN2E6K:btez1bj) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/134e0f213d960bbfa86c05b31db1ed7aa5bfe0b7/tests/Unit/MSFT_xRDRemoteApp.tests.ps1#L197)):*
> ```PowerShell
>                 It 'Should generate an error, given that the CollectionName is not found in the SessionDeployment' {
>                     { Set-TargetResource @xRDRemoteAppSplat -ErrorAction Stop } |
>                         Should -Throw 'Failed to lookup RD Session Collection TestCollection. Error: Collection not found!'
> ```

Also a case for the use of -ExpectedMessage
___
*[tests/Unit/MSFT_xRDRemoteApp.tests.ps1, line 277 at r2](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/88#-MMrAy98EBZYaba4GpjF:-MMrAy98EBZYaba4GpjG:btez1bj) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/134e0f213d960bbfa86c05b31db1ed7aa5bfe0b7/tests/Unit/MSFT_xRDRemoteApp.tests.ps1#L277)):*
> ```PowerShell
>                 It 'Should generate an error, given that the CollectionName is not found in the SessionDeployment' {
>                     { Test-TargetResource @xRDRemoteAppSplat -ErrorAction Stop } |
>                         Should -Throw 'Failed to lookup RD Session Collection TestCollection. Error: Collection not found!'
> ```

Also a case for the use of -ExpectedMessage

**Review by jeremyciak — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/88)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @danielboth)

___
*[tests/Unit/MSFT_xRDRemoteApp.tests.ps1, line 135 at r2](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/88#-MMrAW_gDbGXiZEhl6lO:-MMs60h75MHvSSmQci_P:b42tbv) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/134e0f213d960bbfa86c05b31db1ed7aa5bfe0b7/tests/Unit/MSFT_xRDRemoteApp.tests.ps1#L135)):*
<details><summary><i>Previously, danielboth (Daniël) wrote…</i></summary><blockquote>

I agree this is better that the try - catch approach, please do use -ExpectedMessage though instead of relying on positional parameters.
</blockquote></details>

I didn't even realize that `-ExpectedMessage` was the Parameter name for that part... Oops. I have corrected this in the 3 locations where I omitted it. Thanks!
___
*[tests/Unit/MSFT_xRDRemoteApp.tests.ps1, line 197 at r2](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/88#-MMrAmL71ihHkhLN2E6J:-MMs6EOt5bMVfk7DlFNF:b-896fix) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/134e0f213d960bbfa86c05b31db1ed7aa5bfe0b7/tests/Unit/MSFT_xRDRemoteApp.tests.ps1#L197)):*
<details><summary><i>Previously, danielboth (Daniël) wrote…</i></summary><blockquote>

Also a case for the use of -ExpectedMessage
</blockquote></details>

Done.
___
*[tests/Unit/MSFT_xRDRemoteApp.tests.ps1, line 277 at r2](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/88#-MMrAy98EBZYaba4GpjF:-MMs6FAz7W4Cd1uCyWzI:b-896fix) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/134e0f213d960bbfa86c05b31db1ed7aa5bfe0b7/tests/Unit/MSFT_xRDRemoteApp.tests.ps1#L277)):*
<details><summary><i>Previously, danielboth (Daniël) wrote…</i></summary><blockquote>

Also a case for the use of -ExpectedMessage
</blockquote></details>

Done.

**Review by jeremyciak — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/88)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @danielboth)

___
*[tests/Unit/MSFT_xRDRemoteApp.tests.ps1, line 135 at r2](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/88#-MMrAW_gDbGXiZEhl6lO:-MMs6W3DE75U3vGi7yeF:b-896fix) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/134e0f213d960bbfa86c05b31db1ed7aa5bfe0b7/tests/Unit/MSFT_xRDRemoteApp.tests.ps1#L135)):*
<details><summary><i>Previously, jeremyciak (Jeremy Ciak) wrote…</i></summary><blockquote>

I didn't even realize that `-ExpectedMessage` was the Parameter name for that part... Oops. I have corrected this in the 3 locations where I omitted it. Thanks!
</blockquote></details>

Done.

**Review by danielboth — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/88#-:-MMvpqIe-nyyldr0T8f9:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @jeremyciak)

**Pull request merged**
