### PR TITLE
xRDSessionCollection: Fix Issues #105 and #106

### LINKED ISSUE #105: [xRDSessionCollection] 'fails' when RD configuration settings are applied via GPO
### Problem description

I'm resurrecting issue #34 here, with a proposal on how we should work around it in the suggested solution. I'm happy to raise a PR for the change.

I've experienced the same thing creating a new RDSessionCollection where certain group policy settings are applied to the session hosts in the collection.

As it stands, this problem means DSC has to be applied at least twice in order to stand up a working RDS deployment which adds to the delay.

Thanks.

### Verbose logs

```text
{"time": "2022-09-06T13:40:47.562+01:00", "type": "verbose", "message": "[RDS-BK1]: LCM:  [ Start  Resource ]  [[xRDSessionCollection]collection FooBar Collection]  "},
  {"time": "2022-09-06T13:40:47.587+01:00", "type": "verbose", "message": "[RDS-BK1]: LCM:  [ Start  Test     ]  [[xRDSessionCollection]collection FooBar Collection]  "},
  {"time": "2022-09-06T13:40:48.431+01:00", "type": "verbose", "message": "[RDS-BK1]:                            [[xRDSessionCollection]collection FooBar Collection] Checking for existence of RDSH collection."},
  {"time": "2022-09-06T13:40:48.432+01:00", "type": "verbose", "message": "[RDS-BK1]:                            [[xRDSessionCollection]collection FooBar Collection] Getting information about RDSH collection."},
  {"time": "2022-09-06T13:40:50.326+01:00", "type": "verbose", "message": "[RDS-BK1]: LCM:  [ End    Test     ]  [[xRDSessionCollection]collection FooBar Collection]  in 2.7400 seconds."},
  {"time": "2022-09-06T13:40:50.326+01:00", "type": "verbose", "message": "[RDS-BK1]: LCM:  [ Start  Set      ]  [[xRDSessionCollection]collection FooBar Collection]  "},
  {"time": "2022-09-06T13:40:51.660+01:00", "type": "verbose", "message": "[RDS-BK1]:                            [[xRDSessionCollection]collection FooBar Collection] Creating a new RDSH collection."},
  {"time": "2022-09-06T13:41:03.835+01:00", "type": "error", "message": "The property SecurityLayer is configured by using Group Policy settings. Use the Group Policy Management Console to configure this property."},
  {"time": "2022-09-06T13:41:03.975+01:00", "type": "error", "message": "The property EncryptionLevel is configured by using Group Policy settings. Use the Group Policy Management Console to configure this property."},
  {"time": "2022-09-06T13:44:19.341+01:00", "type": "error", "message": "The property UserAuthenticationRequired is configured by using Group Policy settings. Use the Group Policy Management Console to configure this property."},
  {"time": "2022-09-06T13:44:19.521+01:00", "type": "verbose", "message": "[RDS-BK1]: LCM:  [ End    Set      ]  [[xRDSessionCollection]collection FooBar Collection]  in 209.1950 seconds."},
  {"time": "2022-09-06T13:44:19.526+01:00", "type": "error", "message": "The PowerShell DSC resource '[xRDSessionCollection]collection FooBar Collection' with SourceInfo 'D:\\DscService\\Build\\Modules\\tpRDSConfig\\0.1.0.130\\tpRDSConfig.psm1::391::9::xRDSessionCollection' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details."},
```

### DSC configuration

```powershell
xRDSessionCollection "collection $($collection.CollectionName)" {
            CollectionName       = $collection.CollectionName
            SessionHost          = $collection.SessionHost[0]
            ConnectionBroker     = $ConnectionBroker
            PsDscRunAsCredential = $RDSDeploymentCredential
            DependsOn            = "[xRDSessionDeployment]RdsDeployment"
        }
```

### Suggested solution

Could we add  `-ErrorAction SilentlyContinue` to the [call into](https://github.com/dsccommunity/xRemoteDesktopSessionHost/blob/42739cd37327b8e2437831cae151dc2d6f23dbcf/source/DSCResources/MSFT_xRDSessionCollection/MSFT_xRDSessionCollection.psm1#L66) `New-RDSessionCollection` and then afterwards, check for the presence of the new RDSessionCollection and return success or fail based on whether or not it was created?

### Operating system the target node is running

```text
OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

### PowerShell version and build the target node is running

```text
Name                           Value
----                           -----
PSVersion                      5.1.17763.2931
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.2931
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### xRemoteDesktopSessionHost version

```text
Name                      Version Path
----                      ------- ----
xRemoteDesktopSessionHost 2.1.0   C:\Program Files\WindowsPowerShell\Modules\xRemoteDesktopSessionHost\2.1.0\xRemoteDesktopSessionHost.psd1
```

### LINKED ISSUE #106: xRDSessionCollection: Impossible to add a second Session Collection on Server 2019
### Problem description

This relates to issue #91 which wasn't properly resolved by PR #92

In my use case, I am trying create an RDS deployment with two _RD Session Collections_, uxing `xRDSessionCollection.

The `Test-TargetResource` function in `xRDSessionCollection` relies on `Get-TargetResource`, within the same resource.

`Get-TargetResource` has been amended so that it filters the _RD Session Collections_ on `CollectionName` matching the desired `$CollectionName` if there is *more* than one _RD Session Collection_ returned from `Get-RDSessionCollection`, which had it's filtering removed (bug) when it was migrated from using WMI to CIM for Windows Server 2019.

https://github.com/dsccommunity/xRemoteDesktopSessionHost/blob/b97c82bc6eff7126d4a301f8f58a28ae21002c50/source/DSCResources/MSFT_xRDSessionCollection/MSFT_xRDSessionCollection.psm1#L30

I'm not sure why the change to `xRDSessionCollection` was implemented in this way, with a qualification around the filtering.

In the logs attached, there is no existing _RD Session Collection_ called `Test Collection`, but because `Test-TargetResource` returns true, `Set-TargetResource` is *never* run.

### Verbose logs

```text
{"time": "2022-09-06T15:59:38.575+01:00", "type": "verbose", "message": "[RDS-BK1]: LCM:  [ Start  Resource ]  [[xRDSessionCollection]collection Test Collection]  "},
  {"time": "2022-09-06T15:59:38.591+01:00", "type": "verbose", "message": "[RDS-BK1]: LCM:  [ Start  Test     ]  [[xRDSessionCollection]collection Test Collection]  "},
  {"time": "2022-09-06T15:59:39.763+01:00", "type": "verbose", "message": "[RDS-BK1]:                            [[xRDSessionCollection]collection Test Collection] Checking for existence of RDSH collection."},
  {"time": "2022-09-06T15:59:39.778+01:00", "type": "verbose", "message": "[RDS-BK1]:                            [[xRDSessionCollection]collection Test Collection] Getting information about RDSH collection."},
  {"time": "2022-09-06T15:59:40.528+01:00", "type": "verbose", "message": "[RDS-BK1]: LCM:  [ End    Test     ]  [[xRDSessionCollection]collection Test Collection]  in 1.9380 seconds."},
  {"time": "2022-09-06T15:59:40.528+01:00", "type": "verbose", "message": "[RDS-BK1]: LCM:  [ Skip   Set      ]  [[xRDSessionCollection]collection Test Collection]  "},
  {"time": "2022-09-06T15:59:40.528+01:00", "type": "verbose", "message": "[RDS-BK1]: LCM:  [ End    Resource ]  [[xRDSessionCollection]collection Test Collection]  "},
```

### DSC configuration

```powershell
@{
                        CollectionName                 = 'Main Collection'
                        SessionHost                    = @('rdsh0.somedomain.sometld,rdsh1.somedomain.sometld')
                    }
                    @{
                        CollectionName                 = 'Test Collection'
                        SessionHost                    = @('rdsh2.somedomain.sometld')
                    }

~~~

    foreach ($collection in $Collections) {
        xRDSessionCollection "collection $($collection.CollectionName)" {
            CollectionName       = $collection.CollectionName
            SessionHost          = $collection.SessionHost[0]
            ConnectionBroker     = $ConnectionBroker
            PsDscRunAsCredential = $RDSDeploymentCredential
            DependsOn            = "[xRDSessionDeployment]RdsDeployment"
        }
    }
```

### Suggested solution

Re-implment as:

```
$Collection = Get-RDSessionCollection `
    -CollectionName $CollectionName `
    -ConnectionBroker $ConnectionBroker `
    -ErrorAction SilentlyContinue | `
        Where-Object  CollectionName -eq $CollectionName
```

or

```
    $params = @{
        CollectionName   = $CollectionName
        ConnectionBroker = $ConnectionBroker
        ErrorAction      = 'SilentlyContinue'
    }

    $Collection = Get-RDSessionCollection @params  | `
        Where-Object  CollectionName -eq $CollectionName
```

... depending on preferred layout/coding standards

### Operating system the target node is running

```text
OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

### PowerShell version and build the target node is running

```text
Name                           Value
----                           -----
PSVersion                      5.1.17763.2931
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.2931
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### xRemoteDesktopSessionHost version

```text
Name                      Version Path
----                      ------- ----
xRemoteDesktopSessionHost 2.1.0   C:\Program Files\WindowsPowerShell\Modules\xRemoteDesktopSessionHost\2.1.0\xRemoteDesktopSessionHost.psd1
```

### PR DESCRIPTION
**Pull request by uw-dc**
#### Pull Request (PR) description

This PR supercedes #107 and #108, to hopefully save our future selves time and pain in handling merge conflicts.

***If this PR is merged, please close the two earlier PRs referenced above***

_xRDSessionCollection_'s `Get-TargetResource` has been amended so that it filters the Session Collections returned from `Get-RDSessionCollection` on `CollectionName` matching the desired `$CollectionName`, in all circumstances.

_xRDSessionCollection_ will now ignore errors that are returned from the underlying `New-RDSessionCollection` cmdlet because errors are always returned when certain RD Host GPO settings are applied. _xRDSessionCollection_ as part of `Set-TargetResource` now instead checks whether the desired Session Collection has been created, and if not throws an exception.

#### This Pull Request (PR) fixes the following issues

- Fixes #105
- Fixes #106
- Closes #107 
- Closes #108 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/109)

### CODE REVIEW

**Comment by uw-dc** [comment]
@danielboth sorry to trouble, you; I'm just wondering if it's possible to get a review on this PR please? Been waiting for some months now.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/109)* status: all files reviewed, 3 unresolved discussions (waiting on @uw-dc)

*[a discussion](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/109#-NJLMh7G1p35D3W3pjAg:-NJLMh7H4b9PTjcYgcYj:b-uqel2q) (no related file):*
Could you please change thois line to `windows-latest`? Otherwise the build will fail once merged due to a change in Azure DevOps. 
https://github.com/dsccommunity/xRemoteDesktopSessionHost/blob/42739cd37327b8e2437831cae151dc2d6f23dbcf/azure-pipelines.yml#L28

___
___
*[`source/DSCResources/MSFT_xRDSessionCollection/MSFT_xRDSessionCollection.psm1` line 40 at r1](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/109#-NJLNO7m6ItMZD0nTS8G:-NJLNO7m6ItMZD0nTS8H:bxbk4ci) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/95b85ce5daede38308bf424ae3e58caa594bb61a/source/DSCResources/MSFT_xRDSessionCollection/MSFT_xRDSessionCollection.psm1#L40)):*
> ```PowerShell
>     if ($Collection.Count -eq 0)
>     {
>         return $null
> ```

We should always return all the properties, so we should change this to:



_Suggestion:_
```PowerShell
return @{
    "CollectionName" = $CollectionName
    "SessionHost" = $SessionHost
    "ConnectionBroker" = $ConnectionBroker
    "CollectionDescription" = $null
}
```
___
*[`source/DSCResources/MSFT_xRDSessionCollection/MSFT_xRDSessionCollection.psm1` line 45 at r1](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/109#-NJLOuH4CuTTMqVJPWOt:-NJLOuH4CuTTMqVJPWOu:b-l7okv3) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/95b85ce5daede38308bf424ae3e58caa594bb61a/source/DSCResources/MSFT_xRDSessionCollection/MSFT_xRDSessionCollection.psm1#L45)):*
> ```PowerShell
>     if ($Collection.Count -gt 1)
>     {
>         $CollectionType = $Collection.GetType()
> ```

Suggest we check the types directly like below. But do we need this check, isn't it enough that the count was 2 or more above?  



_Suggestion:_
```PowerShell
        if ($Collection -is [System.Array] -or $Collection.GetType().BaseType -is [System.Array])
        {
            throw 'Non-singular RDSessionCollection in result set'
        }
```

**Comment by uw-dc** [comment]
Thank you for the review. Very much appreciated.

> 
> > ```powershell
> >     if ($Collection.Count -eq 0)
> >     {
> >         return $null
> > ```
> 
> We should always return all the properties, so we should change this to:
> 
> _Suggestion:_
> 
> ```powershell
> return @{
>     "CollectionName" = $CollectionName
>     "SessionHost" = $SessionHost
>     "ConnectionBroker" = $ConnectionBroker
>     "CollectionDescription" = $null
> }
> ```
> 

Returning the properties, but all except `$SessionHost` as null when no existing matching collection is found, on account that there is no `$ensure` property for this resource. (That sounds like a breaking change which should be tackled separately?


> _[`source/DSCResources/MSFT_xRDSessionCollection/MSFT_xRDSessionCollection.psm1` line 45 at r1](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/109#-NJLOuH4CuTTMqVJPWOt:-NJLOuH4CuTTMqVJPWOu:b-l7okv3) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/95b85ce5daede38308bf424ae3e58caa594bb61a/source/DSCResources/MSFT_xRDSessionCollection/MSFT_xRDSessionCollection.psm1#L45)):_
> 
> > ```powershell
> >     if ($Collection.Count -gt 1)
> >     {
> >         $CollectionType = $Collection.GetType()
> > ```
> 
> Suggest we check the types directly like below. But do we need this check, isn't it enough that the count was 2 or more above?
> 
> _Suggestion:_
> 
> ```powershell
>         if ($Collection -is [System.Array] -or $Collection.GetType().BaseType -is [System.Array])
>         {
>             throw 'Non-singular RDSessionCollection in result set'
>         }
> ```

This was a good shout. I checked the type on account that it fixed the tests. On further investigation, the output the original mocks (which I'd copied, pasted and edited) was not a close enough match to the real implementation. It looks like the original logic I wrote was flawed anyway.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/109)* status: all files reviewed, 1 unresolved discussion (waiting on @uw-dc)

___
*[`source/DSCResources/MSFT_xRDSessionCollection/MSFT_xRDSessionCollection.psm1` line 82 at r4](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/109#-NJPtgrbBT1TLwduBYWd:-NJPtgrbBT1TLwduBYWe:bv3lkoc) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/43a705ab9c5c78f0873b0c0e9bf1aa35a98ecd84/source/DSCResources/MSFT_xRDSessionCollection/MSFT_xRDSessionCollection.psm1#L82)):*
> ```PowerShell
>     )
> 
>     $PSBoundParameters.Add('ErrorAction','SilentlyContinue')
> ```

After thinking again around this change I would like to suggest another approach. With the suggested change a user would never know what error occured if the error is any other than those that is "false negatives". 

I would suggest calling the command `New-RDSessionCollection` with `-ErrorAction 'Stop'`. Then wrapping that command in a try-catch-block where the catch block singles out the false positives and re-throws on any (actual) other error. Then we would not need to call Test-TargetResource either.

Something like this where we have a multiple checks for different errors and handles them differently: https://github.com/dsccommunity/ActiveDirectoryDsc/blob/b2838d945204e1153cc3cbfca1a3d90671e0a61c/source/Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1#L2090-L2135



_Code quote:_
```PowerShell
    $PSBoundParameters.Add('ErrorAction','SilentlyContinue')
    Write-Verbose "Creating a new RDSH collection."


    New-RDSessionCollection @PSBoundParameters

    $PSBoundParameters.Remove('ErrorAction')
    if (-not (Test-TargetResource @PSBoundParameters))
```

**Comment by uw-dc** [comment]
> > Reviewed 1 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/109)_ status: all files reviewed, 1 unresolved discussion (waiting on @uw-dc)
> 
> _[`source/DSCResources/MSFT_xRDSessionCollection/MSFT_xRDSessionCollection.psm1` line 82 at r4](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/109#-NJPtgrbBT1TLwduBYWd:-NJPtgrbBT1TLwduBYWe:bv3lkoc) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/43a705ab9c5c78f0873b0c0e9bf1aa35a98ecd84/source/DSCResources/MSFT_xRDSessionCollection/MSFT_xRDSessionCollection.psm1#L82)):_
> 
> > ```powershell
> >     )
> > 
> >     $PSBoundParameters.Add('ErrorAction','SilentlyContinue')
> > ```
> 
> After thinking again around this change I would like to suggest another approach. With the suggested change a user would never know what error occured if the error is any other than those that is "false negatives".
> 
> I would suggest calling the command `New-RDSessionCollection` with `-ErrorAction 'Stop'`. Then wrapping that command in a try-catch-block where the catch block singles out the false positives and re-throws on any (actual) other error. Then we would not need to call Test-TargetResource either.
> 

How about calling `New-RDSessionCollection` with `-ErrorAction Stop` but instead of working through the exception types, we stash the exception and retain the call to `Test-TargetResource`. If the new RDSessionCollection has _not_ been created, then the logic can re-throw?

I think this will keep the logic a bit simpler and given that the RemoteDesktop cmdlets are not that robust, will effectively handle any false-negative situation.

**Comment by johlju** [comment]
Let's try your suggestion.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/109)* status: all files reviewed, 3 unresolved discussions (waiting on @uw-dc)

___
*[`source/DSCResources/MSFT_xRDSessionCollection/MSFT_xRDSessionCollection.psm1` line 85 at r5](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/109#-NJZtty_34PIlmi5sb-_:-NJZtty_34PIlmi5sb-a:b8kxfvz) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/99bae03fb88f1bdb44d443284bc00395cce82869/source/DSCResources/MSFT_xRDSessionCollection/MSFT_xRDSessionCollection.psm1#L85)):*
> ```PowerShell
>     {
>         Write-Verbose "Creating a new RDSH collection."
>         $PSBoundParameters.Add('ErrorAction','SilentlyContinue')
> ```

I think `ErrorAction` needs to be `Stop` for the try-catch to trigger. :thinking: 



_Code quote:_
```PowerShell
$PSBoundParameters.Add('ErrorAction','SilentlyContinue')
```
___
*[`source/DSCResources/MSFT_xRDSessionCollection/MSFT_xRDSessionCollection.psm1` line 86 at r5](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/109#-NJZuUp0-A5whD5tSmx1:-NJZuUp0-A5whD5tSmx2:b-197bkh) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/99bae03fb88f1bdb44d443284bc00395cce82869/source/DSCResources/MSFT_xRDSessionCollection/MSFT_xRDSessionCollection.psm1#L86)):*
> ```PowerShell
>         Write-Verbose "Creating a new RDSH collection."
>         $PSBoundParameters.Add('ErrorAction','SilentlyContinue')
>         New-RDSessionCollection @PSBoundParameters
> ```

Suhhest channging it to the below. Then we don't need to use Add and Remove on the `$PSBoundParameters` (line 85 and 93).



_Suggestion:_
```PowerShell
New-RDSessionCollection @PSBoundParameters -ErrorAction 'Stop'
```
___
*[`source/DSCResources/MSFT_xRDSessionCollection/MSFT_xRDSessionCollection.psm1` line 101 at r5](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/109#-NJZwyE773jxelMuaQXd:-NJZwyE773jxelMuaQXe:bwnk9u6) ([raw file](https://github.com/dsccommunity/xremotedesktopsessionhost/blob/99bae03fb88f1bdb44d443284bc00395cce82869/source/DSCResources/MSFT_xRDSessionCollection/MSFT_xRDSessionCollection.psm1#L101)):*
> ```PowerShell
>             throw $exception
>         }
>         throw ('''Get-RDSessionCollection -CollectionName {0} -ConnectionBroker {1}'' returns empty result set after call to ''New-RDSessionCollection''' -f $CollectionName,$ConnectionBroker)
> ```

Could we concatenate these two by throwing an `ErrorRecord` that passes `$exception` as an `InnerException` maybe? 
https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.errorrecord?view=powershellsdk-1.1.0



_Code quote:_
```PowerShell
        if ($exception)
        {
            throw $exception
        }
        throw ('''Get-RDSessionCollection -CollectionName {0} -ConnectionBroker {1}'' returns empty result set after call to ''New-RDSessionCollection''' -f $CollectionName,$ConnectionBroker)
```

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xremotedesktopsessionhost/109#-:-NJeevGWAXGQlSckPz1v:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uw-dc)

**Comment by johlju** [comment]
Thank you for this @uw-dc! 🙂

**Comment by uw-dc** [comment]
> Thank you for this @uw-dc! 🙂

Thank you!

**Pull request merged**
